blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    # path('activity/<int:pk>/', is_published, name='is_published'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('messaging.urls', namespace='messaging')),
                  path('users/', include('users.urls', namespace='users')),
                  path('', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messaging/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from messaging.apps import MessagingConfig
from messaging.views import (ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView,
                             ClientDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView,
                             MessageDeleteView, MailingListView, MailingDetailView, MailingCreateView,
                             MailingUpdateView, MailingDeleteView, StartListView, mailing_status,
                             toggle_activation)

app_name = MessagingConfig.name

urlpatterns = [
                  path('', StartListView.as_view(), name='start'),

                  path('mailing/', MailingListView.as_view(), name='mailing_list'),
                  path('mailing/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
                  path('mailing/create', MailingCreateView.as_view(), name='mailing_create'),
                  path('mailing/<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
                  path('mailing/<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
                  path('mailing/toggle/<int:mailing_id>/', toggle_activation, name='toggle_activation'),

                  path('message/list', MessageListView.as_view(), name='message_list'),
                  path('message/<int:pk>/', cache_page(60)(MessageDetailView.as_view()), name='message_detail'),
                  path('message/create', MessageCreateView.as_view(), name='message_create'),
                  path('message/<int:pk>/update', MessageUpdateView.as_view(), name='message_update'),
                  path('message/<int:pk>/delete', MessageDeleteView.as_view(), name='message_delete'),

                  path('client/list', ClientListView.as_view(), name='client_list'),
                  path('client/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
                  path('client/create', ClientCreateView.as_view(), name='client_create'),
                  path('client/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),
                  path('client/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),

                  path('mailing/status_list', mailing_status, name='mailing_status'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserResetPasswordView, UserForgotPasswordView, \
    UserPasswordResetConfirmView, ProfileView, user_list, toggle_activation

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path("email_confirm/<str:token>/", email_verification, name='email-confirm'),
    path('reset-password/', UserResetPasswordView.as_view(), name='reset_password'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('', user_list, name='user_list'),
    path('toggle/<int:user_id>/', toggle_activation, name='toggle_activation'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(
        unique=True,
        verbose_name='email'
    )
    phone = models.CharField(
        max_length=35,
        verbose_name='Телефон',
        **NULLABLE,
        help_text='Введите номер телефона'
    )
    avatar = models.ImageField(
        upload_to='users/avatars/',
        **NULLABLE,
        verbose_name='Аватар',
        help_text='Добавьте аватарку'
    )
    country = models.CharField(
        max_length=50,
        verbose_name='Страна',
        **NULLABLE,
        help_text='Укажите Вашу страну'
    )
    token = models.CharField(
        max_length=100,
        verbose_name="Token",
        **NULLABLE
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm, PasswordResetForm, UserChangeForm
from django.forms import BooleanField
from users.models import User
from django import forms


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'country', 'avatar')


class ResetPasswordForm(StyleFormMixin, PasswordResetForm):
    """Форма для сброса пароля"""

    class Meta:
        model = User
        fields = ('email', )


class UserForgotPasswordForm(PasswordResetForm):
    """
    Запрос на восстановление пароля
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class UserSetNewPasswordForm(SetPasswordForm):
    """
    Изменение пароля пользователя после подтверждения
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class UserProfileFrom(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets
import random
import string

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from django.forms import BooleanField
from django.core.exceptions import PermissionDenied
from django.contrib import messages


from users.forms import UserRegisterForm, ResetPasswordForm, UserForgotPasswordForm, UserSetNewPasswordForm, UserProfileFrom
from users.models import User

from config.settings import EMAIL_HOST_USER


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = 'form-check-input'
            else:
                fild.widget.attrs['class'] = 'form-control'


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email_confirm/{token}'
        send_mail(
            subject="Подтверждение почты",
            message=f"Необходимо перейти по ссылке для подтверждения почты {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class UserResetPasswordView(PasswordResetView, StyleFormMixin):
    """
    Сброс пароля с использованием email
    """
    form_class = ResetPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """
        Проверяет валидность и сохраняет новый пароль
        """
        email = form.cleaned_data['email']
        # Проверяем наличие пользователя с указанной почтой
        try:
            user = User.objects.get(email=email)
            if user:
                # Создаем новый пароль для пользователя и отправляем его на почту
                password = ''.join([random.choice(string.digits + string.ascii_letters) for i in range(0, 10)])
                user.set_password(password)
                user.is_active = True
                user.save()
                send_mail(
                    subject='Сброс пароля',
                    message=f'Новый пароль: {password}',
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[user.email]
                )
            return redirect(reverse('users:login'))
        except User.DoesNotExist:
            # Если пользователь не найден, перенаправляем на страницу регистрации
            return redirect(reverse('users:register'))


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Cброс пароля по почте
    """
    form_class = UserForgotPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Письмо с инструкцией по восстановлению пароля отправлена на ваш email'
    subject_template_name = 'users/email/password_subject_reset_mail.txt'
    email_template_name = 'users/email/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на восстановление пароля'
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """
    form_class = UserSetNewPasswordForm
    template_name = 'users/user_password_set_new.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Пароль успешно изменен. Можете авторизоваться на сайте.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileFrom
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def user_list(request):
    user = request.user
    if user.is_authenticated and user.groups.filter(name='manager').exists():
        users = User.objects.all()
        return render(request, 'users/user_list.html', {'users': users})
    raise PermissionDenied


def toggle_activation(request, user_id):
    user = User.objects.get(id=user_id)
    user.is_active = not user.is_active
    user.save()

    action = 'активирован' if user.is_active else 'деактивирован'
    messages.success(request, f'Пользователь {user.email} был {action}.')

    return redirect('users:user_list')  # Перенаправляем обратно в список пользователей

users/templates/users/user_form.html
{% load static %}

<header data-bs-theme="dark">
    {% include 'messaging/includes/inc_main.html' %}
</header>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
</head>
<body>

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <h1>Регистрация</h1>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Зарегестрироваться
                    </button>
                    <div class="btn-group">
                        <a class="btn btn-danger" href="{% url 'messaging:start' %}" role="button">Отмена</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
</body>
</html>

users/templates/users/user_list.html
{% extends 'messaging/base.html' %}
{% load my_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Пользователи</h1>
    <p class="lead">{{ title }}</p>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <table class="table">

                <thead>
                <tr>
                    <th>Пользователь</th>
                    <th>Имя пользователя</th>
                    <th>Телефон</th>
                    <th>Статус</th>
                    <th></th>
                </tr>
                </thead>

                <tbody>
                {% for user in users %}
                <tr>
                    <td><h5 class="text-success">{{ user.email }}</h5></td>
                    <td><h5 class="text-success">{{ user.first_name }}</h5></td>
                    <td><h5 class="text-success">{{ user.phone }}</h5></td>

                    <td>{% if user.is_active %}
                        <h5 class="text-success">Акивен</h5>
                        {% else %}
                        <h5 class="text-danger">Неактивен</h5>
                        {% endif %}
                    </td>

                    <td>
                        {% csrf_token %}
                        <a href="{% url 'users:toggle_activation' user.pk %}">
                            <img src={% if user.is_active %} "/media/users/вкл.png" {% else %}
                            "/media/users/выкл.png" {% endif %} width="70" height="30" class="rounded float-end"></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="col-12">
        <h3> Для просмотра рассылок вам необходимо авторизоваться.</h3>
    </div>
</div>
{% endif %}
{% endblock %}

users/templates/users/user_password_reset.html
{% load static %}

<header data-bs-theme="dark">
    {% include 'messaging/includes/inc_main.html' %}
</header>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
</head>
<body>

<div class="col-12" style="margin-left:20px">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <h4>Запрос на восстановление пароля на сайте</h4>
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">
                            Восстановить пароль
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
</body>
</html>

users/templates/users/user_password_set_new.html
{% load static %}

<header data-bs-theme="dark">
    {% include 'messaging/includes/inc_main.html' %}
</header>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
</head>
<body>

<div class="col-12" style="margin-left:20px">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <h4>Установить новый пароль</h4>
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn btn-success">
                            Подтвердить
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
</body>
</html>