blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    # path('activity/<int:pk>/', is_published, name='is_published'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('messaging.urls', namespace='messaging')),
                  path('users/', include('users.urls', namespace='users')),
                  path('', include('blog.urls', namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messaging/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from messaging.apps import MessagingConfig
from messaging.views import (ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView,
                             ClientDeleteView, MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView,
                             MessageDeleteView, MailingListView, MailingDetailView, MailingCreateView,
                             MailingUpdateView, MailingDeleteView, StartListView, mailing_status,
                             toggle_activation)

app_name = MessagingConfig.name

urlpatterns = [
                  path('', StartListView.as_view(), name='start'),

                  path('mailing/', MailingListView.as_view(), name='mailing_list'),
                  path('mailing/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
                  path('mailing/create', MailingCreateView.as_view(), name='mailing_create'),
                  path('mailing/<int:pk>/update', MailingUpdateView.as_view(), name='mailing_update'),
                  path('mailing/<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
                  path('mailing/toggle/<int:mailing_id>/', toggle_activation, name='toggle_activation'),

                  path('message/list', MessageListView.as_view(), name='message_list'),
                  path('message/<int:pk>/', cache_page(60)(MessageDetailView.as_view()), name='message_detail'),
                  path('message/create', MessageCreateView.as_view(), name='message_create'),
                  path('message/<int:pk>/update', MessageUpdateView.as_view(), name='message_update'),
                  path('message/<int:pk>/delete', MessageDeleteView.as_view(), name='message_delete'),

                  path('client/list', ClientListView.as_view(), name='client_list'),
                  path('client/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
                  path('client/create', ClientCreateView.as_view(), name='client_create'),
                  path('client/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),
                  path('client/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),

                  path('mailing/status_list', mailing_status, name='mailing_status'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, UserResetPasswordView, UserForgotPasswordView, \
    UserPasswordResetConfirmView, ProfileView, user_list, toggle_activation

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path("email_confirm/<str:token>/", email_verification, name='email-confirm'),
    path('reset-password/', UserResetPasswordView.as_view(), name='reset_password'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('', user_list, name='user_list'),
    path('toggle/<int:user_id>/', toggle_activation, name='toggle_activation'),
]

messaging/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Start(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name="Стартовая позиция",
        help_text="Введите стартовые позиции")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Старт'
        verbose_name_plural = 'Старты'


class Client(models.Model):
    first_name = models.CharField(max_length=100, verbose_name="Имя")

    last_name = models.CharField(max_length=100, verbose_name="Фамилия")

    email = models.EmailField(verbose_name="Электронная почта", unique=True)

    comment = models.TextField(verbose_name="Комментарий", **NULLABLE)

    owner = models.ForeignKey(
        User, default=True, on_delete=models.SET_NULL, verbose_name="Владелец", null=True
    )

    def __str__(self):
        return f"{self.last_name} {self.first_name}/n({self.email})"

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name="Тема сообщения")

    message = models.TextField(verbose_name="Сообщение")

    preview = models.ImageField(
        verbose_name="Превью", upload_to="message/preview", **NULLABLE
    )

    created_at = models.DateField(
        auto_now_add=True, verbose_name="Дата создания", **NULLABLE
    )

    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.title} от {self.created_at}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"


class Mailing(models.Model):
    class Periodicity(models.TextChoices):
        DAILY = 'D', 'Ежедневно'
        WEEKLY = 'W', 'Еженедельно'
        MONTHLY = 'M', 'Ежемесячно'

    class Status(models.TextChoices):
        CREATED = 'C', 'Создана'
        RUNNING = 'R', 'Запущена'
        FINISHED = 'F', 'Завершена'

    title = models.CharField(max_length=100, verbose_name="Название рассылки", **NULLABLE)
    preview = models.ImageField(verbose_name="Превью", upload_to='mailing/preview', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name="Сообщение")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания", **NULLABLE)
    clients = models.ManyToManyField(Client, verbose_name="Список клиентов", blank=True)
    at_start = models.DateTimeField(verbose_name='Дата и время начала отправки', **NULLABLE)
    at_end = models.DateTimeField(verbose_name='Дата и время окончания отправки', **NULLABLE)
    periodicity = models.CharField(max_length=1, choices=Periodicity.choices, verbose_name='Периодичность')
    status = models.CharField(max_length=1, verbose_name="Статус рассылки", choices=Status.choices,
                              default=Status.CREATED)
    owner = models.ForeignKey(User, verbose_name="Владелец", on_delete=models.SET_NULL, null=True)
    is_active = models.BooleanField(default=True, verbose_name="")

    def __str__(self):
        return f'Рассылка {self.pk}: {self.title} от {self.created_at},  периодичность - {self.periodicity}, количество клиентов - {self.clients.count()} чел. (статус - {self.status})'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class Attempt(models.Model):
    class Status(models.IntegerChoices):
        SUCCESS = 1, 'Успешно'
        FAILURE = 2, 'Неудачно'

    at_last_attempt = models.DateTimeField(verbose_name='Дата последней попытки', auto_now_add=True, **NULLABLE)
    status = models.SmallIntegerField(choices=Status.choices, verbose_name='Статус попытки', **NULLABLE)
    server_response = models.TextField(verbose_name='Ответ почтового сервера', **NULLABLE, default="")
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='attempts', verbose_name='попытки', **NULLABLE)

    def __str__(self):
        return f'Попытка отправки {self.mailing} от {self.at_last_attempt}'

    class Meta:
        ordering = ['-at_last_attempt']

messaging/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from messaging.forms import ClientForm, MessageForm, MailingCreateForm, MailingForm
from messaging.models import Mailing, Message, Client, Start, Attempt
from blog.models import Blog
from services import get_cache_mailing_active, get_mailing_count_from_cache, get_cache_unique_quantity
from users.models import User


class ClientListView(ListView):
    model = Client
    success_url = reverse_lazy('messaging:client_list')

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            # Возвращаем только клиентов, принадлежащих текущему пользователю
            return Client.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Client.objects.none()


class ClientDetailView(DetailView):
    model = Client
    template_name = 'messaging/client_detail.html'
    success_url = reverse_lazy('messaging:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_item = self.get_object()
        context['title'] = client_item.first_name
        return context


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'messaging/client_form.html'
    success_url = reverse_lazy('messaging:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание клиента'
        return context

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

    def get_queryset(self):
        return Client.objects.all()


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'messaging/client_form.html'
    success_url = reverse_lazy('messaging:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_item = self.get_object()
        context['title'] = client_item.first_name
        return context


class ClientDeleteView(DeleteView):
    model = Client
    template_name = 'messaging/client_confirm_delete.html'
    success_url = reverse_lazy('messaging:client_list')


class MessageListView(ListView):
    model = Message
    success_url = reverse_lazy('messaging:message_list')

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            # Возвращаем только клиентов, принадлежащих текущему пользователю
            return Message.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Message.objects.none()


class MessageDetailView(DetailView):
    model = Message
    template_name = 'messaging/message_detail.html'
    success_url = reverse_lazy('messaging:message_list')


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('messaging:message_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание сообщения'
        return context

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.owner = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('messaging:message_list')


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('messaging:message_list')


class MailingListView(ListView):
    model = Mailing
    success_url = reverse_lazy('messaging:mailing_list')

    def get_queryset(self):
        # Проверяем, аутентифицирован ли пользователь
        if self.request.user.is_authenticated:
            if self.request.user.groups.filter(name='manager').exists():
                # Возвращаем все рассылки
                return Mailing.objects.all()
            # Возвращаем только рассылки, принадлежащих текущему пользователю
            return Mailing.objects.filter(owner=self.request.user)
        # Возвращаем пустой queryset для неаутентифицированных пользователей
        return Mailing.objects.none()


def toggle_activation(request, mailing_id):
    mailing = Mailing.objects.get(pk=mailing_id)
    mailing.is_active = not mailing.is_active
    mailing.save()

    action = 'активирован' if mailing.is_active else 'деактивирован'
    messages.success(request, f'Пользователь {mailing.title} был {action}.')

    return redirect('messaging:mailing_detail', pk=mailing.id)  # Перенаправляем обратно в список пользователей


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'messaging/mailing_detail.html'
    success_url = reverse_lazy('messaging:mailing_form')

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     mailing_item = self.get_object()
    #     context['title'] = mailing_item.time_sending
    #     return context


class MailingCreateView(CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'messaging/mailing_form.html'
    success_url = reverse_lazy('messaging:mailing_list')
    permission_required = 'messaging.mailing_create'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание рассылки'
        return context

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['clients'].queryset = Client.objects.filter(owner=self.request.user)
        form.fields['message'].queryset = Message.objects.filter(owner=self.request.user)
        return form

    def get_queryset(self):
        return Mailing.objects.all()


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('messaging:mailing_list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['clients'].queryset = Client.objects.filter(owner=self.request.user)
        form.fields['message'].queryset = Message.objects.filter(owner=self.request.user)
        return form


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('messaging:mailing_list')


class StartListView(ListView):
    model = Blog
    template_name = 'messaging/start_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing_quantity_active'] = get_cache_mailing_active()
        context['mailing_quantity'] = get_mailing_count_from_cache()
        context['clients_unique_quantity'] = get_cache_unique_quantity()
        context['records'] = Blog.objects.order_by('?')[:3]
        return context


def mailing_status(request):
    mailings = Mailing.objects.prefetch_related('attempts').all()
    return render(request, 'messaging/mailing_status.html', {'mailings': mailings})

messaging/templates/messaging/client_list.html
{% extends 'messaging/base.html' %}
{% load my_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="pricing-header px-3 py-3 pt-md-3 pb-md-3 mx-auto text-center">
    <h1 class="display-4">Клиенты</h1>
</div>


<div class="py-5 text-center container">
    <div class="col-lg-12 col-md-8 mx-auto">
        {% if user.is_authenticated %}
        <p>
            <a type="button" class="btn btn-lg btn-block btn-outline-success"
               href="{% url 'messaging:client_create' %}">
                Добавить клиента</a>
        </p>
        {% endif %}
    </div>
</div>


<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h4 class="my-0 font-weight-normal">{{object.email}}</h4>
                        <h1 class="card-title pricing-card-title"> {{object.first_name}}</h1>
                        <div class="d-flex justify-content-between align-items-center">
                            {% if user.is_authenticated %}
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'messaging:client_detail' object.pk %}"
                                   role="button">Информация</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-info" href="{% url 'messaging:client_update' object.pk %}"
                                   role="button">Редактировать</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-danger" href="{% url 'messaging:client_delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<div class="container">
        <div class="col-12">
            <h3> Для добавления получателей рассылок вам необходимо авторизоваться.</h3>
        </div>
    </div>
{% endif %}

{% endblock %}

messaging/templates/messaging/mailing_detail.html
{% extends 'messaging/base.html' %}
{% load my_tags %}
{% block content %}


<main class="container">
    <div class="row mb-2">
        <div class="d-grid gap-2 col-6 mx-auto">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-lg h-md-250 position-relative bg-white">

                <div class="d-grid gap-2 col-2 ms-4 mt-4">
                    <img src="/media/message/email.png" alt="mdo" width="120" height="120">
                </div>

                <div class="col p-4 d-flex flex-column position-static">
                    <h2 class="mb-0 ms-3"><strong>{{ mailing.title }}</strong></h2>
                    <div class="mb-1 mb-4 text-body-secondary">от {{ mailing.created_at }}</div>
                    <h5 class="mb-0 mb-3"><strong>Тема
                        сообщения: </strong>{{ mailing.message.title | truncatechars:35 }}</h5>

                    <div class="row">
                        <div class="col-5" class="mb-1 text-body-secondary">Дата начала отправки:</div>
                        <div class="col" class="mb-1 text-body-secondary">{{ mailing.at_start }}</div>
                    </div>

                    <div class="row">
                        <div class="col-5" class="mb-1 text-body-secondary">Дата следующей отправки:</div>
                        <div class="col" class="mb-1 text-body-secondary">{{ current_datetime }}</div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-5" class="mb-1 text-body-secondary">Дата окончания отправки:</div>
                        <div class="col" class="mb-1 text-body-secondary">{{ mailing.at_end }}</div>
                    </div>

                    <div class="row">
                        <div class="col-5" class="mb-1 text-body-secondary">Периодичность отправки:</div>
                        <div class="col" class="mb-1 text-body-secondary">{{ mailing.get_periodicity_display }}</div>
                    </div>

                    <div class="row">
                        <div class="col-5" class="mb-1 text-body-secondary">Статус рассылки:</div>
                        <div class="col" class="mb-1 text-body-secondary">{{ mailing.get_status_display }}</div>
                    </div>

                    <div class="col text-danger mt-2">
                        {% if not mailing.is_active and not perms.mailing.change_mailing %}
                        <strong>Рассылка отключена, обратитесь к администратору</strong>
                        {% endif %}
                    </div>

                    <h5 class="mb-0 mt-3 mb-1">В списке
                        рассылки {{ mailing.clients.count }} {{ mailing.clients.count | clients_word_form }}:</h5>
                    <ul>
                        {% for client in mailing.clients.all %}
                        <li>{{ client.first_name }} {{ client.last_name }}</li>
                        <!-- Adjust fields as necessary -->
                        {% empty %}
                        <li>Нет клиентов для этой рассылки.</li>
                        {% endfor %}
                    </ul>

                    <div class="d-grid gap-2 d-md-flex mt-5 justify-content-md-end">
                        {% if perms.mailing.change_mailing %}

                        {% if mailing.is_active %}
                        <a class="btn btn-success" href="{% url 'messaging:toggle_activation' mailing.pk %}"
                           role="button" style="width: 130px;">Отключить</a>
                        {% else %}
                        <a class="btn btn-danger" href="{% url 'messaging:toggle_activation' mailing.pk %}"
                           role="button" style="width: 130px;">Включить</a>
                        {% endif %}

                        {% endif %}

                        {% if mailing.owner == user %}
                        <a class="btn btn-primary" href="{% url 'messaging:mailing_update' mailing.pk %}"
                           role="button" style="width: 130px;">Редактировать</a>
                        <a class="btn btn-primary" href="{% url 'messaging:mailing_delete' mailing.pk %}"
                           role="button" style="width: 130px;">Удалить</a>
                        {% endif %}

                        <a class="btn btn-primary" href="{% url 'messaging:mailing_list' %}" role="button"
                           style="width: 130px;">Назад</a>
                    </div>

                </div>

            </div>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-lg h-md-250 position-relative bg-white">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Название рассылки</th>
                        <th>Статус</th>
                        <th>Попытки</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{{ mailing.title }}</td>
                        <td>{{ mailing.get_status_display }}</td>
                        <td>
                            <ul>
                                {% for attempt in mailing.attempts.all %}
                                <li>{{ attempt.at_last_attempt }}
                                    - {{ attempt.get_status_display }}: {{ attempt.server_response }}
                                </li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>

{% endblock %}

messaging/templates/messaging/mailing_list.html
{% extends 'messaging/base.html' %}
{% load my_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылка</h1>
    <p class="lead">{{ title }}</p>
</div>
<div class="py-5 text-center container">
    <div class="col-lg-12 col-md-8 mx-auto">
        {% if user.is_authenticated %}
        <p>
            <a type="button" class="btn btn-lg btn-block btn-outline-success"
               href="{% url 'messaging:mailing_create' %}">
                Добавить сообщение</a>
        </p>
        {% endif %}
    </div>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-6 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">
                            {{object.subject|title}}</h4>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">Сообщение:</h1>
                            <h3 class="card-title pricing-card-title">{{ object.message }}</h3>
                            <h6 class="card-title pricing-card-title">Статус рассылки: {{ object.get_status_display }}</h6>
                            <h7 class="card-title pricing-card-title">Периодичность рассылки: {{ object.get_periodicity_display }}</h7>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            </ul>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'messaging:mailing_detail' object.pk %}">
                                Подробнее
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-warning"
                               href="{% url 'messaging:mailing_update' object.pk %}">
                                Изменить
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-danger"
                               href="{% url 'messaging:mailing_delete' object.pk %}">
                                Удалить
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <div class="col-12">
        <h3> Для просмотра рассылок вам необходимо авторизоваться.</h3>
    </div>
</div>
{% endif %}
{% endblock %}

messaging/templates/messaging/message_list.html
{% extends 'messaging/base.html' %}
{% load my_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сообщения</h1>
</div>

<div class="py-5 text-center container">
    <div class="col-lg-12 col-md-8 mx-auto">
        <p>
            <a type="button" class="btn btn-lg btn-block btn-outline-success"
               href="{% url 'messaging:message_create' %}">
                Добавить сообщение</a>
        </p>
    </div>
</div>

<form method="post" action="" class="form-floating">
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for message in object_list %}
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-md-12">
                            <div class="row g-0 border rounded overflow-hidden flex-md-row shadow-lg h-md-250 position-relative bg-white">

                                <div class="col-2 mt-1 mb-1 d-none d-lg-block">
                                    {% if message.preview %}
                                    <img src="{{ message.preview | media_filter }}" alt="mdo" width="80"
                                         height="80">
                                    {% else %}
                                    <img src="/media/message/email.png" alt="mdo" width="80"
                                         height="80">
                                    {% endif %}
                                </div>

                                <div class="col p-4 d-flex flex-column position-static">
                                    <h4 class=><strong>{{ message.title }}</strong></h4>
                                    <div class="text-body-secondary">{{ message.created_at }}</div>
                                    <a href="{% url 'messaging:message_detail' message.pk %}"
                                       class="icon-link gap-1 icon-link-hover stretched-link"></a>
                                </div>
                            </div>
                            {% if user.is_authenticated %}
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'messaging:message_detail' message.pk %}"
                                   role="button">Информация</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-info" href="{% url 'messaging:message_update' message.pk %}"
                                   role="button">Редактировать</a>
                            </div>
                            <div class="btn-group">
                                <a class="btn btn-danger" href="{% url 'messaging:message_delete' message.pk %}"
                                   role="button">Удалить</a>
                            </div>
                            {% endif %}
                        </div>

                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% else %}
<div class="container">
        <div class="col-12">
            <h3> Для добавления сообщений для рассылок вам необходимо авторизоваться.</h3>
        </div>
    </div>
{% endif %}
{% endblock %}